[options]
db_host = 192.168.1.201
db_port = 5432
db_user = odoo
db_password = odoo
data_dir = /var/lib/odoo
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$DyGEMOYcA6AUglCKsfae8w$eQJca6/XDWuLc4sOKmgPecL9jNyBlFYqFMQYopbtDKQynrl2D.m4MHL6eLMyrROQzBYHqnS9QW40sHytvlbHJQ
workers = 8
limit_time_real = 3600
limit_time_cpu = 1800
limit_memory_soft = 21474836480
limit_memory_hard = 25769803776
limit_request = 8192
max_cron_threads = 2
